language: clojure

jvm:
    - openjdk7
    - oraclejdk7
    - openjdk6

lein: lein2

script: lein2 test; cat nginx.log

before_install:
    - sudo apt-get update
    - sudo apt-get install nginx

branches:
    only:
        - master
